name: PlayerLore
version: '${project.version}'
main: dansplugins.playerlore.PlayerLore
api-version: 1.13

commands:
  playerlore:
  pl:

permissions:
  pl.help:
    default: true
  pl.add:
    default: true
  pl.edit:
    default: true
  pl.remove:
    default: true