name: ExamplePonderPlugin
version: v0.2-alpha-1
main: dansplugins.playerlore.ExamplePonderPlugin
api-version: 1.13

commands:
  exampleponderplugin:
  epp:

permissions:
  epp.help:
    default: true
